FROM ubuntu:latest
#Prepare platform
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update
RUN apt-get install git maven iputils-ping -y
#Prepare box
WORKDIR /usr
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello
WORKDIR boxfuse-sample-java-war-hello
CMD mvn package
