FROM ubuntu:latest
#Prepare platform
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update
RUN apt-get install git maven -y
#Prepare box
WORKDIR /usr/box 
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello
WORKDIR /boxfuse-sample-java-war-hello
RUN mvn package
WORKDIR /target
COPY hello-1.0.war ./target
